# ???????????????? Application ??????????????????????????????????????????????
spring.application.name=taskmanager
server.port=${PORT:8080}
# ???????????????? Railway Cloud MySQL (Direct Connection) ????????????????????
spring.datasource.url=jdbc:mysql://root:pvVEGuZMZGTqlxwViLPFAobasICIuCeJ@acela.proxy.rlwy.net:16518/railway
spring.datasource.username=root
spring.datasource.password=pvVEGuZMZGtqlxwViLPFAobasICIuCeJ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ???????????????? JPA / Hibernate ??????????????????????????????????????????
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ???????????????? JWT ??????????????????????????????????????????????????????
app.jwt.secret=R4un4kCh4ubeyTh1sIsMySup3rS3cr3tKey2026!
app.jwt.expiration-ms=3600000

# ???????????????? Scheduler ????????????????????????????????????????????????
app.scheduler.overdue-tasks-cron=0 0 6 * * *

# ???????????????? Pagination defaults ??????????????????????????????????????
app.pagination.default-size=10
app.pagination.max-size=50
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html